# Generated by Django 5.0.7 on 2024-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('vid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=23)),
                ('l_name', models.CharField(max_length=23)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=23)),
                ('pincode', models.IntegerField()),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=23)),
                ('city', models.CharField(max_length=23)),
                ('state', models.CharField(max_length=23)),
            ],
        ),
    ]
